export { default as AuthRoutes } from "./AuthRoutes"
export { default as CustomersRoutes } from "./CustomersRoutes"
export { default as DashboardRoutes } from "./DashboardRoutes"
export { default as DriversRoutes } from "./DriversRoutes"
export { default as RidersRoutes } from "./RidersRoutes"
export { default as RolesRoutes } from "./RolesRoutes"
export { default as TripsRoutes } from "./TripsRoutes"
export { default as VehiclesRoutes } from "./VehiclesRoutes"